### ISSUE TITLE
Items deleted merging across servers 

### ISSUE THREAD

**Issue by Madscience763** [MultiPaper/MultiPaper#262]
https://user-images.githubusercontent.com/104371439/190873641-dbc4c999-0690-4e14-a59c-5a7923e1c577.mp4

**Comment by x4n4th** [comment]
It would be easier and potentially more performant if each individual server merged Item Entities it owns. You would end up with two stacks on each side of the boundary.

**Comment by ham1255** [comment]
i can't replicate this behavior, tried what done in the video about but can't replicate

**Comment by Madscience763** [comment]
> i can't replicate this behavior, tried what done in the video about but can't replicate

How many times did you try? it can sometimes not happen

It still happens to me, now with an error

[12:17:32 WARN]: java.lang.Exception: Sending an empty entity EntityItem['Air'/3220212, uuid='f893a3cd-cb05-4f9e-ab5f-c1b7437d6c17', l='ServerLevel[world]', x=-63.81, y=-62.12, z=6.21, cpos=[-4, 0], tl=3, v=false, removed=DISCARDED]
[12:17:32 WARN]:        at puregero.multipaper.externalserverprotocol.EntityUpdateNBTPacket.<init>(EntityUpdateNBTPacket.java:41)
[12:17:32 WARN]:        at puregero.multipaper.MultiPaperEntitiesHandler.lambda$onChunkMove$0(MultiPaperEntitiesHandler.java:142)
[12:17:32 WARN]:        at puregero.multipaper.MultiPaper.broadcastPacketToExternalServers(MultiPaper.java:234)
[12:17:32 WARN]:        at puregero.multipaper.MultiPaperEntitiesHandler.lambda$onChunkMove$1(MultiPaperEntitiesHandler.java:142)
[12:17:32 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:17:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:154)
[12:17:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:17:32 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1372)
[12:17:32 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190)
[12:17:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:17:32 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1349)
[12:17:32 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1342)
[12:17:32 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bq(IAsyncTaskHandler.java:114)
[12:17:32 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1478)
[12:17:32 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1204)
[12:17:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313)
[12:17:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ham1255** [comment]
Actully tried around 16 times but no items were deleted

**Comment by Madscience763** [comment]
What did you have the simulation and view distance set to?

**Comment by ham1255** [comment]
Both are 10

**Comment by Madscience763** [comment]
Can you try 4 simulation and 6 render distance? 
Also set the item merge-radius in spigot.yml to 5

**Comment by ham1255** [comment]
I haven't changed the default values yet but i have same exact error 
when throwing items in same way in that video but items do not get deleted.
```
[16:51:40 WARN]: java.lang.Exception: Sending an empty entity EntityItem['Air'/25482, uuid='ccf28994-9214-4ae9-81d3-6698be47b13d', l='ServerLevel[world]', x=-159.69, y=101.80, z=-159.88, cpos=[-10, -10], tl=3, v=false, removed=DISCARDED]
[16:51:40 WARN]: 	at puregero.multipaper.externalserverprotocol.EntityUpdateNBTPacket.<init>(EntityUpdateNBTPacket.java:41)
[16:51:40 WARN]: 	at puregero.multipaper.MultiPaperEntitiesHandler.lambda$onChunkMove$0(MultiPaperEntitiesHandler.java:142)
[16:51:40 WARN]: 	at puregero.multipaper.MultiPaper.broadcastPacketToExternalServers(MultiPaper.java:234)
[16:51:40 WARN]: 	at puregero.multipaper.MultiPaperEntitiesHandler.lambda$onChunkMove$1(MultiPaperEntitiesHandler.java:142)
[16:51:40 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:51:40 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:154)
[16:51:40 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:51:40 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1372)
[16:51:40 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190)
[16:51:40 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[16:51:40 WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1349)
[16:51:40 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1342)
[16:51:40 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bq(IAsyncTaskHandler.java:114)
[16:51:40 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1478)
[16:51:40 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1204)
[16:51:40 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313)
[16:51:40 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ham1255** [comment]
tested your Values no items getting deleted.

**Comment by Madscience763** [comment]
it might be a plugin then, thanks
