### ISSUE TITLE
Failed to get system info for World Generation

### ISSUE THREAD

**Issue by MrEnxo** [MultiPaper/MultiPaper#280]
```
[08:26:34 ERROR]: Encountered an unexpected exception
org.spongepowered.configurate.serialize.SerializationException: [environment, nether-ceiling-void-damage-height] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "disabled"
        at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:346) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:254) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]
        at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:216) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: org.spongepowered.configurate.serialize.SerializationException: [fixes, falling-block-height-nerf] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "disabled"
                at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:346) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:254) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
                at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]
                at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
                at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:216) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
                at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
                at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]
                Suppressed: org.spongepowered.configurate.serialize.SerializationException: [fixes, tnt-entity-height-nerf] of type java.lang.Integer: java.lang.NumberFormatException: For input string: "disabled"
                        at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:346) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:254) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
                        at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]
                        at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
                        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:216) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
                        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
                        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
                        at java.lang.Thread.run(Thread.java:833) ~[?:?]
                Caused by: java.lang.NumberFormatException: For input string: "disabled"
                        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
                        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
                        at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344) ~[configurate-core-4.1.2.jar:?]
                        ... 17 more
        Caused by: java.lang.NumberFormatException: For input string: "disabled"
                at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
                at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
                at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344) ~[configurate-core-4.1.2.jar:?]
                ... 17 more
Caused by: java.lang.NumberFormatException: For input string: "disabled"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344) ~[configurate-core-4.1.2.jar:?]
        ... 17 more
[08:26:34 ERROR]:       Cause of unexpected exception was
java.lang.NumberFormatException: For input string: "disabled"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at org.spongepowered.configurate.serialize.NumericSerializers.parseNumber(NumericSerializers.java:344) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$9(NumericSerializers.java:254) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
        at org.spongepowered.configurate.ConfigurationNode.require(ConfigurationNode.java:407) ~[configurate-core-4.1.2.jar:?]
        at io.papermc.paper.configuration.Configurations.initializeWorldDefaultsConfiguration(Configurations.java:154) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:216) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:26:34 WARN]: Failed to get system info for World Generation
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.storage.SaveData.B()" because "this.m" is null
        at net.minecraft.server.MinecraftServer.lambda$fillSystemReport$16(MinecraftServer.java:1730) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.SystemReport.setDetail(SystemReport.java:62) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.fillSystemReport(MinecraftServer.java:1729) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:26:34 ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2022-10-23_08.26.34-server.txt
```
This Happens On Startup of my server.
0 Clue whats going on here. Paper was previously installed on this machine, but thats the only reason i could see why this is happening. But that makes 0 sense

**Comment by PureGero** [comment]
Your paper world configuration is invalid.
