### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by GatitoUwU** [MultiPaper/MultiPaper#301]
Hello, I'm running 10 instances of MultiPaper (with a load balancer ofc) and when it surpasses 150 players, some instances randomly die.
```[20:46:01] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1592) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:455) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1428) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.papermc.paper.world.ChunkEntitySlices.removeEntity(net.minecraft.world.entity.Entity, int)" because "slices" is null
	at io.papermc.paper.world.EntitySliceManager.removeEntity(EntitySliceManager.java:69) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager$Callback.onRemove(PersistentEntitySectionManager.java:641) ~[?:?]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4604) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.unloadEntity(PersistentEntitySectionManager.java:378) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$processChunkUnload$11(PersistentEntitySectionManager.java:366) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.storeChunkSections(PersistentEntitySectionManager.java:343) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.processChunkUnload(PersistentEntitySectionManager.java:365) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$processUnloads$12(PersistentEntitySectionManager.java:384) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at it.unimi.dsi.fastutil.longs.LongCollection.removeIf(LongCollection.java:285) ~[fastutil-8.5.6.jar:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.processUnloads(PersistentEntitySectionManager.java:383) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.tick(PersistentEntitySectionManager.java:420) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:738) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1573) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	... 5 more
[20:46:01] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: Cannot invoke "io.papermc.paper.world.ChunkEntitySlices.removeEntity(net.minecraft.world.entity.Entity, int)" because "slices" is null
	at io.papermc.paper.world.EntitySliceManager.removeEntity(EntitySliceManager.java:69) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager$Callback.onRemove(PersistentEntitySectionManager.java:641) ~[?:?]
	at net.minecraft.world.entity.Entity.setRemoved(Entity.java:4604) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.unloadEntity(PersistentEntitySectionManager.java:378) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$processChunkUnload$11(PersistentEntitySectionManager.java:366) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.storeChunkSections(PersistentEntitySectionManager.java:343) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.processChunkUnload(PersistentEntitySectionManager.java:365) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$processUnloads$12(PersistentEntitySectionManager.java:384) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at it.unimi.dsi.fastutil.longs.LongCollection.removeIf(LongCollection.java:285) ~[fastutil-8.5.6.jar:?]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.processUnloads(PersistentEntitySectionManager.java:383) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.tick(PersistentEntitySectionManager.java:420) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:738) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1573) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:455) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1428) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by ham1255** [comment]
This no longer a thing anymore, it seems like was paper issue?
