### ISSUE TITLE
Server crash error

### ISSUE THREAD

**Issue by Shizuri23** [MultiPaper/MultiPaper#338]
[19:30:19] [Server thread/WARN]: java.lang.Exception: Tried to update the nbt of player Yudachi_Kai_2 to {}
[19:30:19] [Server thread/WARN]: 	at puregero.multipaper.externalserverprotocol.EntityUpdateNBTPacket.loadEntity(EntityUpdateNBTPacket.java:103)
[19:30:19] [Server thread/WARN]: 	at puregero.multipaper.externalserverprotocol.EntityUpdateNBTPacket.lambda$handle$0(EntityUpdateNBTPacket.java:73)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:154)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1374)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:201)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1351)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1344)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:137)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1322)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1210)
[19:30:19] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[19:30:19] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/46082179/216966967-2cce3b2c-9d08-4967-8311-3a21c7c6099a.png">

**Comment by Shizuri23** [comment]
Sit on the head of the player on another server, and then he uses the coleoptera to fly

**Comment by Shizuri23** [comment]
> [19:30:19] [Server thread/WARN]: java.lang.Exception: Tried to update the nbt of player Yudachi_Kai_2 to {}
> [19:30:19] [Server thread/WARN]: at puregero.multipaper.externalserverprotocol.EntityUpdateNBTPacket.loadEntity(EntityUpdateNBTPacket.java:103)
> [19:30:19] [Server thread/WARN]: at puregero.multipaper.externalserverprotocol.EntityUpdateNBTPacket.lambda$handle$0(EntityUpdateNBTPacket.java:73)
> [19:30:19] [Server thread/WARN]: at net.minecraft.server.TickTask.run(TickTask.java:18)
> [19:30:19] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:154)
> [19:30:19] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
> [19:30:19] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1374)
> [19:30:19] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:201)
> [19:30:19] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
> [19:30:19] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1351)
> [19:30:19] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1344)
> [19:30:19] [Server thread/WARN]: at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:137)
> [19:30:19] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1322)
> [19:30:19] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1210)
> [19:30:19] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
> [19:30:19] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
> <img alt="image" width="1024" src="https://user-images.githubusercontent.com/46082179/216966967-2cce3b2c-9d08-4967-8311-3a21c7c6099a.png">

When this error occurs, the server will be very stuck
