### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by YTiceice** [MultiPaper/MultiPaper#367]
I don't know how this is triggered, but I see this error keep recurring in the console, and it happens so fast that it crashes my server
```
[00:38:05] [Server thread/WARN]: [EntityUpdateWithDependenciesPacket] Could not find entity a47fab6c-0df5-4e80-aa5e-153ad1ef5bbf for PacketPlayOutMount, requesting it
[00:38:05] [Server thread/WARN]: java.lang.Exception: Tried to update the nbt of player Venatise to {}
[00:38:05] [Server thread/WARN]: 	at puregero.multipaper.externalserverprotocol.EntityUpdateNBTPacket.loadEntity(EntityUpdateNBTPacket.java:115)
[00:38:05] [Server thread/WARN]: 	at puregero.multipaper.externalserverprotocol.EntityUpdateNBTPacket.lambda$handle$0(EntityUpdateNBTPacket.java:74)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:154)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1374)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:201)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1351)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1344)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bq(IAsyncTaskHandler.java:114)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1480)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1200)
[00:38:05] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[00:38:05] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
MultiPaper version: `git-MultiPaper-"bc53f8e" (MC: 1.19.3)* Previous version: git-Paper-448 (MC: 1.19.3)`

If you need more information from me, please let me know, thank you very much

**Comment by YTiceice** [comment]
This seems to be a bug caused by CMI's sit function...
