### ISSUE TITLE
Player is either on another team or not on any team. Cannot remove from team 'PVP-07530806979d'

### ISSUE THREAD

**Issue by Crazed981** [MultiPaper/MultiPaper#368]
Presumably because of the PvpManager plugin
```
[22:35:34 ERROR]: Error executing task on Server
java.lang.IllegalStateException: Player is either on another team or not on any team. Cannot remove from team 'PVP-07530806979d'.
        at net.minecraft.world.scores.Scoreboard.removePlayerFromTeam(Scoreboard.java:229) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.ServerScoreboard.removePlayerFromTeam(ServerScoreboard.java:121) ~[?:?]
        at puregero.multipaper.externalserverprotocol.ScoreboardUpdatePacket.handle(ScoreboardUpdatePacket.java:116) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at puregero.multipaper.externalserverprotocol.ScoreboardUpdatePacket.lambda$handle$0(ScoreboardUpdatePacket.java:86) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:154) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1372) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:190) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1349) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1342) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:137) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1320) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:313) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-37]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by PureGero** [comment]
Yeah, probably because of the PvpManager plugin. If the plugin is syncing the scoreboard by itself, you can disable multipaper's syncing under `sync-settings.sync-scoreboards=false`
