### ISSUE TITLE
Exception: Sending an empty entity TextDisplay

### ISSUE THREAD

**Issue by FreeSoccerHDX** [MultiPaper/MultiPaper#378]
Error:
`[21:56:54 WARN]: java.lang.Exception: Sending an empty entity TextDisplay['Text Display'/3768487, uuid='b819c837-a77e-49ca-a710-679373a4a236', l='ServerLevel[world]', x=-1385.52, y=72.74, z=162.04, cpos=[-87, 10], tl=186, v=true]
[21:56:54 WARN]:        at puregero.multipaper.externalserverprotocol.EntityUpdateNBTPacket.<init>(EntityUpdateNBTPacket.java:42)
[21:56:54 WARN]:        at puregero.multipaper.externalserverprotocol.RequestEntityPacket.lambda$handle$0(RequestEntityPacket.java:66)
[21:56:54 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:56:54 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:154)
[21:56:54 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:56:54 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1371)
[21:56:54 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:201)
[21:56:54 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[21:56:54 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1348)
[21:56:54 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1341)
[21:56:54 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:137)
[21:56:54 WARN]:        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1319)
[21:56:54 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1207)
[21:56:54 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[21:56:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
`

Code:
`textDisplay = (TextDisplay) location.getWorld().spawnEntity(location, EntityType.TEXT_DISPLAY); 
  textDisplay.setText(text);
  textDisplay.setAlignment(alignment);
  textDisplay.setBillboard(billboard);
  textDisplay.setShadowed(false);
  textDisplay.setPersistent(false);`

**Comment by PureGero** [comment]
Fixed in 1.20.1 dev builds

**Comment by PureGero** [comment]
It was fixed less than 2 hours ago.

**Comment by FreeSoccerHDX** [comment]
Ahh sry my bad didnt watch at the end of the commits (they were reversed)
Thanks for your fast Help! Great Work!
