### ISSUE TITLE
Citizens do not work correctly

### ISSUE THREAD

**Issue by TaylorEevee** [MultiPaper/MultiPaper#387]
### Expected behavior

Hello, when I installed the Citizens plug-in，I created an npc.The plug-in is not working properly

### Observed/Actual behavior

[19:19:14 WARN]: Invalid UUID was passed, possible a plugin doing weird stuff?, you can safely ignore this if you are using such plugins: Invalid UUID string: Citizens
[19:19:14 WARN]: [Citizens] Task #76 for Citizens v2.0.32-SNAPSHOT (build 3147) generated an exception
java.lang.NullPointerException: Cannot read field "h" because "server" is null
        at net.minecraft.stats.ServerStatsCounter.<init>(ServerStatsCounter.java:61) ~[?:?]
        at net.citizensnpcs.nms.v1_20_R1.util.EmptyServerStatsCounter.<init>(EmptyServerStatsCounter.java:14) ~[Citizens-2.0.32-b3147.jar:?]
        at net.citizensnpcs.nms.v1_20_R1.entity.EntityHumanNPC.D(EntityHumanNPC.java:210) ~[Citizens-2.0.32-b3147.jar:?]
        at net.minecraft.server.players.PlayerList.getPlayerStats(PlayerList.java:1581) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-14]
        at net.minecraft.server.level.ServerPlayer.<init>(ServerPlayer.java:437) ~[?:?]
        at net.citizensnpcs.nms.v1_20_R1.entity.EntityHumanNPC.<init>(EntityHumanNPC.java:69) ~[Citizens-2.0.32-b3147.jar:?]
        at net.citizensnpcs.nms.v1_20_R1.entity.HumanController.createEntity(HumanController.java:43) ~[Citizens-2.0.32-b3147.jar:?]
        at net.citizensnpcs.npc.AbstractEntityController.create(AbstractEntityController.java:24) ~[Citizens-2.0.32-b3147.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:302) ~[Citizens-2.0.32-b3147.jar:?]
        at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:185) ~[Citizens-2.0.32-b3147.jar:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[Citizens-2.0.32-b3147.jar:?]
        at net.citizensnpcs.Citizens$CitizensLoadTask.run(Citizens.java:632) ~[Citizens-2.0.32-b3147.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-14]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-14]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1133) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-14]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-14]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps/models to reproduce

install citizens,create a npc

### Plugin and Datapack List

Citizens-2.0.32-b3147

### MultiPaper version

multipaper-1.20.1-14

**Comment by PureGero** [comment]
Unfortunately Citizens utilises NMS and thus is not supported by MultiPaper. If you wish for Citizens to work with MultiPaper, reach out to them, or develop a multipaper-compatible fork of Citizens.
