### ISSUE TITLE
Player Passengar EntityUpdateNBTPacket

### ISSUE THREAD

**Issue by FreeSoccerHDX** [MultiPaper/MultiPaper#388]
### Expected behavior

No errors

### Observed/Actual behavior

java.lang.Exception: Sending an empty entity EntityPlayer[..........]
at puregero.multipaper.externalserverprotocol.EntityUpdateNBTPacket.<init>(EntityUpdateNBTPacket.java:42)
at puregero.multipaper.externalserverprotocol.RequestEntityPacket.lambda$handle$0(RequestEntityPacket.java:66)

### Steps/models to reproduce

Player1 joins Server1 and adds a Passengar to him self

Player2 joins Server2 and trys the same

Infinity error log spam with errors lines like above

### Plugin and Datapack List

Empty

### MultiPaper version

MultiPaper-1.20.1-14 (MC: 1.20.1)

**Comment by PureGero** [comment]
How does Player1 add a passenger to himself?

**Comment by FreeSoccerHDX** [comment]
Player1 gets a passenger (ArmorStand) in the PlayerJoinEvent (also tested with a delay)
