### ISSUE TITLE
ERROR: Couldn't place player in world

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [MultiPaper/MultiPaper#394]
### Expected behavior

Players can join the server normally.

### Observed/Actual behavior

Players cannot join the server.

### Steps/models to reproduce

I dont know how to reproduce this problems exactly because this bug is always existing and all the players cannot join the server at all.
If you need further information just contact me and I'll try again.

### Plugin and Datapack List

```
> plugins
[19:54:47 INFO]: Bukkit Plugins: (40):
[19:54:47 INFO]:  - AllMusic, Brewery, Citizens, CMILib, CoreProtect, dynmap, eco, EcoEnchants, EliteMobs, GrimAC
[19:54:47 INFO]:  GSit, HolographicDisplays, ImageOnMap, libreforge, LiteBans, LiteSignIn, LuckPerms, Maintenance, Matrix, mcMMO
[19:54:47 INFO]:  MoeTeleport, MythicMobs, NetworkInterceptor, OpenInv, PistonMOTD, PlaceholderAPI, PluginManager, ProtocolLib, QuickShop, RealisticSeasons
[19:54:47 INFO]:  Residence, SkinsRestorer, *SnowballDamage, spark, TAB, Vault, WorldBorder, WorldEdit, WorldGuard, XConomy
```

### MultiPaper version

```
> version
[20:00:00 INFO]: Checking version, please wait...
[20:00:03 INFO]: Current: MultiPaper-1.20.1-21 (MC: 1.20.1)*
You are running the latest version
```

### Other

The server log says 
```
[19:54:34 INFO]: UUID of player Shiroame_Kusu is a102c161-5673-4154-89d3-6846fec50ba3
[19:54:35 ERROR]: Couldn't place player in world
net.minecraft.ReportedException: Sending packet
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2367) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2345) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.internalTeleport(ServerGamePacketListenerImpl.java:1967) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1896) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1876) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1872) ~[?:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:316) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-21]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:613) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1631) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-21]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-21]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1427) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-21]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1198) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-21]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:327) ~[multipaper-1.20.1.jar:MultiPaper-1.20.1-21]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: type cannot be null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar:?]
        at com.comphenix.protocol.injector.StructureCache.getStructure(StructureCache.java:138) ~[ProtocolLib(1).jar:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:126) ~[ProtocolLib(1).jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:96) ~[ProtocolLib(1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib(1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib(1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib(1).jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib(1).jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:451) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:394) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2359) ~[?:?]
        ... 17 more
[19:54:35 INFO]: Shiroame_Kusu lost connection: Invalid player data
[19:54:35 INFO]: Shiroame_Kusu left the game
```

**Comment by Shiroiame-Kusu** [comment]
I saw the com.comphenix.protocol in the error stack so I wonder is this a bug that related to multipaper or Protocollib?

**Comment by PureGero** [comment]
Try removing each plugin one by one until it starts working (except for Protocollib). This will let us figure out which plugin is causing the issue.

Also, try testing if this issue occurs with paper 1.20.1 as well.
